# docker-compose.yml
version: '3.1'

networks:
  default:
    driver: bridge

volumes:
  mongo_data: {}

services:
#  web:
#    build:
#    # build from Dockerfile
#      context: ./Path
#      dockerfile: Dockerfile
#    ports:
#     - "5000:5000"
#    volumes:
#     - .:/code

  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    # restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
